-- Tablas espejo para E2E en el mismo proyecto de Supabase.
-- No reemplazan ni modifican las tablas productivas.
--
-- Luego de ejecutar este script, configura:
-- SUPABASE_RESPUESTAS_TABLE=respuestas_e2e
-- SUPABASE_RESPUESTAS_BLOQUEADAS_TABLE=respuestas_bloqueadas_e2e

CREATE TABLE IF NOT EXISTS public.respuestas_e2e (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  edad integer NOT NULL CHECK (edad > 0),
  sexo text NOT NULL,
  respuesta_1 text,
  respuesta_2 text,
  respuesta_3 text,
  created_at timestamp with time zone DEFAULT now(),
  pais_residencia text,
  nacionalidad text,
  ip_address text,
  ip_country text,
  respondent_id text,
  CONSTRAINT respuestas_e2e_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS respuestas_e2e_respondent_id_unique
  ON public.respuestas_e2e (respondent_id);

CREATE TABLE IF NOT EXISTS public.respuestas_bloqueadas_e2e (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  nombre text NOT NULL,
  edad integer NOT NULL CHECK (edad > 0),
  sexo text NOT NULL,
  pais_residencia text NOT NULL,
  nacionalidad text NOT NULL,
  respondent_id text NOT NULL,
  motivo_bloqueo text NOT NULL,
  ip_address text,
  ip_country text
);

CREATE UNIQUE INDEX IF NOT EXISTS respuestas_bloqueadas_e2e_respondent_id_unique
  ON public.respuestas_bloqueadas_e2e (respondent_id);
